DROP TABLE IF EXISTS users;
CREATE TABLE users (
  user_id INTEGER PRIMARY KEY AUTO_INCREMENT,
  username VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL,
  password VARCHAR(255) NOT NULL
);

DROP TABLE IF EXISTS followers;
CREATE TABLE followers
(
  who_id INTEGER,
  whom_id INTEGER
);

DROP TABLE IF EXISTS messages;
CREATE TABLE messages (
  message_id INTEGER PRIMARY KEY AUTO_INCREMENT,
  user_id INTEGER NOT NULL,
  text VARCHAR(255) NOT NULL,
  pub_date INTEGER,
  flagged INTEGER
);
