stages:
  - test
  - name: deploy
    if: branch = production

services:
  - docker

jobs:
  include:
    - stage: test
      script: 
        - docker build -t freakency/devops_minitwit_app .
        - docker build -t freakency/devops_minitwit_api .

    - stage: deploy
      provider: script
      script: ./travis_stages/deploy.sh
      on:
        branch: production

script : skip
