version: '3.5'

networks:
  main:
    driver: bridge

services:
  app:
    image: freakency/devops_minitwit_app
    container_name: devops_minitwit_app
    volumes:
      - /root/db:/var/www/db
    ports:
      - "80:80"
    networks:
      - main
    depends_on:
      - grafana
      - prometheus

  api:
    image: freakency/devops_minitwit_api
    container_name: devops_minitwit_api
    volumes:
      - /root/db:/var/www/db
    ports:
      - "1337:1337"
    networks:
      - main
    depends_on:
      - app
      - grafana
      - prometheus

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - main

  grafana:
    image: grafana/grafana:4.5.2
    environment:
      - GF_INSTALL_PLUGINS=mtanda-histogram-panel,briangann-gauge-panel
    container_name: grafana
    volumes:
      - ./grafana-storage:/var/lib/grafana
    ports:
      - "3000:3000"
    networks:
      - main
