version: "3.5"

networks:
  main:
    driver: bridge

services:
  minitwit:
    build: .
    image: freakency/devops
    container_name: minitwit
    volumes:
      - /var/www/db:/var/www/db
    ports:
      - "80:80"
      - "1337:1337"
    networks:
      - main
    depends_on:
      - grafana
      - prometheus

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - main

  grafana:
    image: grafana/grafana:4.5.2
    environment:
      - GF_INSTALL_PLUGINS=mtanda-histogram-panel,briangann-gauge-panel
    container_name: grafana
    volumes:
      - ./grafana-storage:/var/lib/grafana
    ports:
      - "3000:3000"
    networks:
      - main
