version: "3.5"

networks:
  main:
    driver: bridge

services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx
    networks:
      - main
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro

  app:
    build: ./app
    image: freakency/devops_minitwit_app
    container_name: devops_minitwit_app
    volumes:
      - /root/db:/var/www/db
      - /root/log:/var/www/log
    networks:
      - main
    depends_on:
      - grafana
      - prometheus
      - nginx-proxy
    environment:
      - VIRTUAL_HOST=minitwit.janschill.de

  api:
    build: ./api
    image: freakency/devops_minitwit_api
    container_name: devops_minitwit_api
    volumes:
      - /root/db:/var/www/db
      - /root/log:/var/www/log
    ports:
      - "1337:1337"
    networks:
      - main
    depends_on:
      - app
      - grafana
      - prometheus
      - nginx-proxy
    environment:
      - VIRTUAL_HOST=minitwit-api.janschill.de

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - /root/minitwit/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - main

  grafana:
    image: grafana/grafana:4.5.2
    environment:
      - GF_INSTALL_PLUGINS=mtanda-histogram-panel,briangann-gauge-panel
    container_name: grafana
    volumes:
      - ./grafana-storage:/var/lib/grafana
    ports:
      - "3000:3000"
    networks:
      - main

  stalker:
    image: freakency/devops_minitwit_stalker
    container_name: devops_minitwit_stalker
    volumes:
      - /root/log:/var/www/stalker/log
    networks:
      - main
