global:
  scrape_interval: 60s
  evaluation_interval: 60s

  external_labels:
    monitor: "codelab-monitor"

rule_files:
  - "prometheus.rules.yml"

scrape_configs:
  - job_name: "itu-minitwit-app"

    static_configs:
      - targets: ["devops_minitwit_app:80"]
        labels:
          group: "production"

  - job_name: "itu-minitwit-api"

    static_configs:
      - targets: ["devops_minitwit_api:1337"]
        labels:
          group: "production"
