uris:
  - protocol: "http"
    address: "46.101.119.181"
    port: "11501"
    path: "/"
  - protocol: "http"
    address: "46.101.119.181"
    port: "11501"
    path: "/public"
  - protocol: "http"
    address: "46.101.119.181"
    port: "11501"
    path: "/login"
  - protocol: "http"
    address: "46.101.119.181"
    port: "11501"
    path: "/register"
