# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

gem 'roda'
gem 'dotenv'
gem 'sequel'
gem 'bcrypt'
gem 'sqlite'
gem 'rubocop', require: false
gem 'json'
