# frozen_string_literal: true

source 'https://rubygems.org'

git_source(:github) { |repo_name| "https://github.com/#{repo_name}" }

gem 'bcrypt'
gem 'json'
gem 'prometheus-client'
gem 'rake'
gem 'roda'
gem 'sequel'
gem 'sqlite3'
gem 'tilt'
gem 'logger'

group :developement do
  gem 'rubocop', require: false
  gem 'rubocop-rspec', require: false
  gem 'rubycritic', require: false
end
