name: Deploy files

on:
  push:
    branches: [ production ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Copy docker-compose.yml via scp
      uses: appleboy/scp-action@master
      env:
        HOST: ${{ secrets.REMOTE_HOST }}
        USERNAME: "root"
        PORT: 22
        KEY: ${{ secrets.SERVER_SSH_KEY }}
      with:
        source: "docker-compose.yml"
        target: "/root/minitwit"
    - name: Copy prometheus.yml via scp
      uses: appleboy/scp-action@master
      env:
        HOST: ${{ secrets.REMOTE_HOST }}
        USERNAME: "root"
        PORT: 22
        KEY: ${{ secrets.SERVER_SSH_KEY }}
      with:
        source: "prometheus.yml"
        target: "/root/minitwit"
